/**
 * siyuan-agent-system 知識發布配接器的冪等安裝程式。
 *
 * 預設為 dry-run，只驗證並印出計畫；加上 --apply 才會寫入三樣東西，全部位於
 * 目標專案內：配接器設定（.omp/siyuan-memory.json）、OMP 擴充套件 stub
 * （.omp/extensions/siyuan-memory.ts），以及專案層的擴充註冊
 * （.omp/config.yml 的 extensions；`disabledExtensions` 只在需要帶入繼承來的
 * 全域項目時才會被碰觸）。
 *
 * 本程式不主張任何自動記憶擁有權：Hindsight 的 `hindsight.*` 設定與既有的
 * `disabledExtensions` 項目（含 jev-memory-gate 的停用狀態）一律原樣保留，
 * 環境中的 `HINDSIGHT_AUTO_*`／`JEV_GATE_MODE` 也不是拒絕安裝的理由。它只註冊
 * 自己的 stub，也不主動回填或還原任何先前寫入的設定。
 *
 * stub 以絕對路徑繫結到本次**實際驗證過**的配接器；--adapter 指到哪裡，stub 就
 * 載入哪裡。已建置配接器另以內容 manifest（`omp-memory.manifest.json`）核對輸出
 * 與來源（entry、capture、state、contracts 等）是否仍一致，不只比對單檔 mtime。
 *
 * stub 另以絕對路徑寫進專案 `extensions`：OMP 對 `.omp/extensions/*.ts` 的原生
 * 探索走 gitignore 過濾（`globIf` 帶 gitignore:true），而 stub 依設計是
 * gitignored，因此只有顯式註冊才會被載入。`extensions` 與
 * `disabledExtensions` 一樣是陣列覆蓋語意，繼承的全域項目必須顯式帶上，否則
 * 專案層的覆寫會靜默丟掉使用者原本的全域設定。
 *
 * 本程式不修改全域設定、不寫入其他專案、不重設既有啟用邊界或佇列，也從不輸出
 * 權杖或憑據內容。預設的全域設定檔位置完全依原生 OMP 的路徑規則解析（agent 目錄
 * 決定於 PI_CODING_AGENT_DIR／PI_CONFIG_DIR／profile，檔名取 config.yml，不存在
 * 時用 config.yaml）；profile 值本身不合法時無法可靠判定，會要求明確的
 * --global-config，而不是只發警告後照樣覆蓋全域清單。專案 YAML 以逐行編輯加上
 * 套用後語意驗證完成，任何未預期的鍵值變動都會中止並保留原檔。
 */
import {
  lstat,
  mkdir,
  open,
  readFile,
  realpath,
  rename,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { getAgentDir, MAIN_CONFIG_FILENAMES, resolveProfileEnv } from "@oh-my-pi/pi-utils/dirs";
import { MAX_TOKEN_BYTES, serviceOriginSchema } from "../integrations/omp/config.ts";
import {
  ADAPTER_MANIFEST_NAME,
  type AdapterManifest,
  hashFile,
  parseAdapterManifest,
} from "./adapter-manifest.ts";

const REPO_ROOT = dirname(import.meta.dir);
const ADAPTER_DEFAULT = "dist/omp-memory.js";
const CONFIG_RELATIVE = join(".omp", "siyuan-memory.json");
const SETTINGS_RELATIVE = join(".omp", "config.yml");
const STUB_RELATIVE = join(".omp", "extensions", "siyuan-memory.ts");
const STATE_RELATIVE = join(".omp", "siyuan-memory-state");
/** 生成 stub 的第一行；同時作為「本工具產生」的辨識標記。 */
const STUB_MARKER =
  "// Generated by `bun run setup-omp -- --apply`; edit the adapter, not this file.";

/**
 * 專案 stub 的內容契約：繫結到本次實際驗證過的配接器**絕對路徑**。絕對路徑是刻意
 * 的——stub 位於目標專案內，相對路徑會解析到目標專案而不是來源專案。
 */
function generatedStub(adapterPath: string): string {
  return `${STUB_MARKER}
// Loaded by OMP as the project extension "siyuan-memory".
export { default } from ${JSON.stringify(adapterPath)};
`;
}

const PROJECT_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;

const USAGE = `用法：bun run setup-omp -- [選項]

必填（--apply 或 dry-run 皆需要，--status 除外）：
  --project <絕對路徑>     目標 OMP 專案根目錄（預設：目前工作目錄）
  --project-id <id>        知識服務的專案 ID（[A-Za-z0-9._:-]，最長 64）
  --service-url <url>      知識服務的完整來源，必須與伺服器 PUBLIC_ORIGIN 一致
                           （預設 http://localhost:8787；若用 127.0.0.1 連線，
                           PUBLIC_ORIGIN 必須明確設成同一個 origin）
  --token-file <絕對路徑>  配接器權杖檔案（只檢查存在與大小，不讀取內容）

選填：
  --state-dir <絕對路徑>   配接器本機狀態目錄（預設：<專案>/.omp/siyuan-memory-state）
  --activated-at <ISO 時間> 首次啟用邊界；既有啟用需搭配 --reconfigure 才能變更
  --config <絕對路徑>      設定檔位置（預設：<專案>/.omp/siyuan-memory.json 或 SIYUAN_MEMORY_CONFIG）
  --adapter <路徑>         已建置的配接器（預設：<repo>/dist/omp-memory.js）；stub 會以
                           絕對路徑繫結到這裡，改動既有的繫結需搭配 --reconfigure
  --global-config <路徑>   全域 OMP 設定（絕對路徑；預設：原生 agent 目錄下的 config.yml，
                           不存在時改用 config.yaml；agent 目錄由 PI_CODING_AGENT_DIR 或
                           OMP_PROFILE／PI_PROFILE 決定，兩者都無法可靠判定時必須明確指定）
  --apply                  實際寫入；未指定時只做 dry-run
  --reconfigure            允許變更既有啟用的專案／服務／權杖／狀態範圍
  --status                 只印出非機密的生效目標與就緒狀態（配接器以 stub 實際繫結的
                           路徑為判準；明確指定 --adapter 時兩者必須一致）
  --help                   顯示本說明

離開碼：0 成功、1 驗證或寫入失敗、2 參數錯誤。`;

class SetupError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly exitCode = 1,
  ) {
    super(message);
    this.name = "SetupError";
  }
}

interface Options {
  project: string;
  projectId?: string;
  serviceUrl?: string;
  tokenFile?: string;
  stateDir?: string;
  activatedAt?: string;
  configPath?: string;
  adapterPath?: string;
  globalConfigPath?: string;
  apply: boolean;
  reconfigure: boolean;
  status: boolean;
  help: boolean;
}

interface TargetPaths {
  root: string;
  configPath: string;
  settingsPath: string;
  stubPath: string;
  stateDir: string;
}

interface MemoryConfig {
  schemaVersion: 1;
  enabled: boolean;
  projectId: string;
  projectRoot: string;
  serviceUrl: string;
  tokenFile: string;
  stateDir: string;
  activatedAt: string;
}

interface SettingsPlan {
  text: string;
  changed: boolean;
  /** 本次要補進 `disabledExtensions` 的條目：只有繼承來的全域項目。 */
  additions: string[];
  /** 本次要補進 `extensions` 的條目：繼承的全域項目加上 stub 絕對路徑。 */
  extensionAdditions: string[];
  globalIds: string[];
  globalPath: string;
}

interface StubState {
  exists: boolean;
  path: string;
  /** 既有 stub 目前繫結的配接器絕對路徑；無法解析時為 null。 */
  boundPath: string | null;
}

interface Plan {
  options: Options;
  paths: TargetPaths;
  config: MemoryConfig;
  activatedAtSource: string;
  scopeChanges: string[];
  tokenSummary: string;
  adapterSummary: string;
  /** 本次實際驗證過的配接器絕對路徑；stub 就繫結到這裡。 */
  adapterPath: string;
  /** stub 需要的動作：建立、維持既有繫結、或在 --reconfigure 後重寫。 */
  stubAction: "create" | "keep" | "rewrite";
  settings: SettingsPlan;
  stub: StubState;
  warnings: string[];
}

function usageError(message: string): SetupError {
  return new SetupError("usage", `${message}\n\n${USAGE}`, 2);
}

type StringOptionKey =
  | "project"
  | "projectId"
  | "serviceUrl"
  | "tokenFile"
  | "stateDir"
  | "activatedAt"
  | "configPath"
  | "adapterPath"
  | "globalConfigPath";

function parseArgs(argv: string[]): Options {
  const options: Options = {
    project: process.cwd(),
    apply: false,
    reconfigure: false,
    status: false,
    help: false,
  };
  const valued: Record<string, StringOptionKey> = {
    "--project": "project",
    "--project-id": "projectId",
    "--service-url": "serviceUrl",
    "--token-file": "tokenFile",
    "--state-dir": "stateDir",
    "--activated-at": "activatedAt",
    "--config": "configPath",
    "--adapter": "adapterPath",
    "--global-config": "globalConfigPath",
  };
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index] ?? "";
    const [flag, inline] =
      arg.startsWith("--") && arg.includes("=")
        ? (arg.split(/=(.*)/s, 2) as [string, string])
        : [arg, undefined];
    if (
      flag === "--apply" ||
      flag === "--reconfigure" ||
      flag === "--status" ||
      flag === "--help"
    ) {
      if (inline !== undefined) throw usageError(`${flag} 不接受值。`);
      if (flag === "--apply") options.apply = true;
      if (flag === "--reconfigure") options.reconfigure = true;
      if (flag === "--status") options.status = true;
      if (flag === "--help") options.help = true;
      continue;
    }
    const key = valued[flag];
    if (!key) throw usageError(`未知參數：${arg}`);
    const value = inline ?? argv[++index];
    if (value === undefined || value === "" || value.startsWith("--"))
      throw usageError(`${flag} 需要一個值。`);
    options[key] = value;
  }
  if (options.status && (options.apply || options.reconfigure)) {
    throw usageError("--status 不能與 --apply 或 --reconfigure 同時使用。");
  }
  return options;
}

function requireFlag(value: string | undefined, flag: string): string {
  if (!value) throw usageError(`缺少必要參數 ${flag}。`);
  return value;
}

async function statOrNull(target: string) {
  try {
    return await lstat(target);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

async function realpathNearest(target: string): Promise<string> {
  let current = resolve(target);
  for (;;) {
    try {
      return await realpath(current);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    const parent = dirname(current);
    if (parent === current) return current;
    current = parent;
  }
}

function isInside(parent: string, child: string): boolean {
  const rel = relative(parent, child);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

/**
 * 兩個路徑是否指向同一個檔案。以 realpath 比較，才不會被符號連結或相對寫法騙過；
 * 任一邊解析不到（例如檔案已被刪除）時退回比較正規化後的絕對路徑，讓「明確指定了
 * 不同檔案」與「同一條已消失的路徑」仍然可分。
 */
async function sameFile(left: string, right: string): Promise<boolean> {
  const [a, b] = await Promise.all([
    realpath(left).catch(() => resolve(left)),
    realpath(right).catch(() => resolve(right)),
  ]);
  return a === b;
}

async function resolveProjectRoot(raw: string): Promise<string> {
  if (!isAbsolute(raw)) {
    throw new SetupError("project_not_absolute", `--project 必須是絕對路徑（收到 ${raw}）。`);
  }
  const info = await statOrNull(raw);
  if (!info) throw new SetupError("project_missing", `找不到專案目錄 ${raw}。`);
  if (info.isSymbolicLink())
    throw new SetupError("project_is_symlink", `--project 不得是符號連結（${raw}）。`);
  if (!info.isDirectory()) throw new SetupError("project_not_directory", `${raw} 不是目錄。`);
  return await realpath(raw);
}

function resolveConfigPath(options: Options, projectRoot: string): string {
  const configured = options.configPath ?? process.env.SIYUAN_MEMORY_CONFIG?.trim();
  if (!configured) return join(projectRoot, CONFIG_RELATIVE);
  const resolved = isAbsolute(configured) ? configured : resolve(projectRoot, configured);
  return resolved;
}

/**
 * 預設全域設定檔完全沿用原生 OMP 18.2.3 的規則：原生 agent 目錄下的 `config.yml`，
 * 不存在時才用 `config.yaml`（`MAIN_CONFIG_FILENAMES` 的順序與原生設定載入器一致）；
 * agent 目錄來自原生 `getAgentDir()`，因此 `PI_CODING_AGENT_DIR`、`PI_CONFIG_DIR` 與
 * OMP_PROFILE／PI_PROFILE 指定的 named profile 都算在內。
 *
 * profile 值本身不合法時是唯一無法可靠判定的情況：原生 CLI 會直接報錯，但模組載入
 * 階段的解析會靜默退回預設 profile。此時若照預設路徑讀取，就可能讀錯檔案，再用專案層
 * 「整份覆蓋」的語意把真正的全域 extensions／disabledExtensions 丟掉，所以這裡要求
 * 明確的 --global-config 並中止，而不是只發警告後照樣覆蓋。
 */
async function resolveGlobalConfigPath(explicit: string | undefined): Promise<string> {
  if (explicit !== undefined) {
    if (!isAbsolute(explicit)) {
      throw new SetupError(
        "global_config_not_absolute",
        `--global-config 必須是絕對路徑（收到 ${explicit}）。`,
      );
    }
    return explicit;
  }
  try {
    resolveProfileEnv(process.env.OMP_PROFILE, process.env.PI_PROFILE);
  } catch {
    throw new SetupError(
      "global_config_profile_invalid",
      "OMP_PROFILE／PI_PROFILE 指定的 profile 名稱不合法，無法可靠判定全域設定檔；請修正環境變數，或改用 --global-config 明確指定實際使用的檔案。",
    );
  }
  const agentDir = getAgentDir();
  for (const filename of MAIN_CONFIG_FILENAMES) {
    const candidate = join(agentDir, filename);
    // 原生探索與設定載入器都是「讀到了就用，讀不到才往後退」：不存在、目錄、壞連結或
    // 權限不足都算讀不到，因此這裡也用實際讀取判定，而不是看 lstat 存不存在。
    const readable = await readFile(candidate, "utf8").then(
      () => true,
      () => false,
    );
    if (readable) return candidate;
  }
  return join(agentDir, MAIN_CONFIG_FILENAMES[0]);
}

async function assertWritableTarget(
  label: string,
  target: string,
  projectRoot: string,
): Promise<void> {
  const parentReal = await realpathNearest(dirname(target));
  if (!isInside(projectRoot, parentReal)) {
    throw new SetupError(
      "path_escapes_project",
      `${label} ${target} 的目錄透過符號連結指向專案外（${parentReal}）；請改用專案內的一般目錄。`,
    );
  }
  const info = await statOrNull(target);
  if (!info) return;
  if (info.isSymbolicLink()) {
    throw new SetupError("path_is_symlink", `${label} ${target} 是符號連結，本工具拒絕覆寫。`);
  }
  if (!info.isFile()) {
    throw new SetupError("path_not_file", `${label} ${target} 不是一般檔案。`);
  }
}

async function resolveTargetPaths(options: Options, projectRoot: string): Promise<TargetPaths> {
  const paths: TargetPaths = {
    root: projectRoot,
    configPath: resolveConfigPath(options, projectRoot),
    settingsPath: join(projectRoot, SETTINGS_RELATIVE),
    stubPath: join(projectRoot, STUB_RELATIVE),
    stateDir: options.stateDir ?? join(projectRoot, STATE_RELATIVE),
  };
  if (!isAbsolute(paths.stateDir)) {
    throw new SetupError(
      "state_dir_not_absolute",
      `--state-dir 必須是絕對路徑（收到 ${paths.stateDir}）。`,
    );
  }
  await assertWritableTarget("設定檔", paths.configPath, projectRoot);
  await assertWritableTarget("專案設定", paths.settingsPath, projectRoot);
  await assertWritableTarget("擴充套件 stub", paths.stubPath, projectRoot);
  const stateInfo = await statOrNull(paths.stateDir);
  if (stateInfo && !stateInfo.isDirectory()) {
    throw new SetupError(
      "state_dir_not_directory",
      `--state-dir ${paths.stateDir} 已存在但不是目錄。`,
    );
  }
  return paths;
}

function parseMemoryConfig(value: unknown, sourcePath: string): MemoryConfig {
  const fail = (detail: string): never => {
    throw new SetupError(
      "config_invalid",
      `${sourcePath} 的設定無效：${detail}；請修復或刪除後再執行。`,
    );
  };
  if (value === null || typeof value !== "object" || Array.isArray(value))
    return fail("最上層必須是物件");
  const record = value as Record<string, unknown>;
  const expected = [
    "schemaVersion",
    "enabled",
    "projectId",
    "projectRoot",
    "serviceUrl",
    "tokenFile",
    "stateDir",
    "activatedAt",
  ];
  for (const key of Object.keys(record)) {
    if (!expected.includes(key)) return fail(`出現未預期的欄位 ${key}`);
  }
  if (record.schemaVersion !== 1) return fail("schemaVersion 必須是 1");
  if (typeof record.enabled !== "boolean") return fail("enabled 必須是布林值");
  for (const key of [
    "projectId",
    "projectRoot",
    "serviceUrl",
    "tokenFile",
    "stateDir",
    "activatedAt",
  ] as const) {
    if (typeof record[key] !== "string" || (record[key] as string).trim() === "")
      return fail(`${key} 必須是非空字串`);
  }
  const config = record as unknown as MemoryConfig;
  if (!PROJECT_ID_PATTERN.test(config.projectId)) return fail("projectId 格式不符");
  for (const key of ["projectRoot", "tokenFile", "stateDir"] as const) {
    if (!isAbsolute(config[key])) return fail(`${key} 必須是絕對路徑`);
  }
  // runtime 的 schema 只收純來源：帶路徑／查詢／片段／帳密或尾端斜線的舊設定在這裡
  // 就必須現形，否則 --status 會把它當成可用的啟用設定（假就緒）。
  if (!serviceOriginSchema.safeParse(config.serviceUrl).success) {
    return fail(
      "serviceUrl 必須是純 http(s) 來源（scheme://host[:port]），不可含路徑、查詢、片段或帳密",
    );
  }
  if (!Number.isFinite(Date.parse(config.activatedAt))) return fail("activatedAt 必須是 ISO 時間");
  return config;
}

async function readExistingConfig(configPath: string): Promise<MemoryConfig | null> {
  const info = await statOrNull(configPath);
  if (!info) return null;
  if (info.isSymbolicLink())
    throw new SetupError("config_is_symlink", `${configPath} 是符號連結，本工具拒絕覆寫。`);
  if (!info.isFile()) throw new SetupError("config_not_file", `${configPath} 不是一般檔案。`);
  const text = await readFile(configPath, "utf8");
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    throw new SetupError(
      "config_unreadable",
      `${configPath} 不是有效 JSON；請修復或刪除後再執行。`,
    );
  }
  return parseMemoryConfig(value, configPath);
}

/**
 * `--service-url` 只接受純來源（origin）。判準只有一個：runtime 也用的
 * `serviceOriginSchema`；這裡只多做一種無害正規化——純來源末端多寫一個斜線。
 * 其餘形狀（路徑、查詢、片段、帳密、非 http(s)、過長）一律拒絕，錯誤碼只用來說明
 * URL 哪個部分不合格，不是第二份判準。
 */
function normalizeServiceUrl(raw: string): string {
  const direct = serviceOriginSchema.safeParse(raw);
  if (direct.success) return direct.data;
  const reason = direct.error.issues[0]?.message ?? "不符合來源網址規則。";
  if (raw.endsWith("/")) {
    const trimmed = serviceOriginSchema.safeParse(raw.slice(0, -1));
    if (trimmed.success) return trimmed.data;
  }
  throw serviceUrlError(raw, reason);
}

function serviceUrlError(raw: string, reason: string): SetupError {
  let url: URL | null = null;
  try {
    url = new URL(raw);
  } catch {
    url = null;
  }
  if (!url) return new SetupError("service_url_invalid", `--service-url ${raw} 不是有效網址。`);
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    return new SetupError("service_url_invalid", `--service-url ${raw} 必須是 http 或 https。`);
  }
  if (url.username || url.password) {
    return new SetupError("service_url_has_credentials", "--service-url 不得內嵌帳號或密碼。");
  }
  if (url.search || url.hash) {
    return new SetupError("service_url_has_query", "--service-url 不得包含查詢字串或片段。");
  }
  // 到這裡只剩「有路徑、尾端斜線不止一個，或超過長度上限」。原因直接引用共用 schema
  // 自己的說明，免得同一條規則被寫成第二份實作。
  return new SetupError(
    "service_url_not_origin",
    `--service-url ${raw} 不可用（${reason}）；必須是純來源 ${url.origin}，不可包含路徑。`,
  );
}

function validateIsoTime(raw: string): string {
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/.test(raw)) {
    throw new SetupError("activated_at_invalid", `--activated-at ${raw} 不是 ISO 8601 時間。`);
  }
  if (!Number.isFinite(Date.parse(raw))) {
    throw new SetupError("activated_at_invalid", `--activated-at ${raw} 無法解析。`);
  }
  return raw;
}

async function inspectTokenFile(
  raw: string,
  projectRoot: string,
  warnings: string[],
): Promise<{ path: string; summary: string }> {
  if (!isAbsolute(raw)) {
    throw new SetupError("token_file_not_absolute", `--token-file 必須是絕對路徑（收到 ${raw}）。`);
  }
  const info = await statOrNull(raw);
  if (!info)
    throw new SetupError("token_file_missing", `找不到權杖檔案 ${raw}；請先建立配接器權杖。`);
  if (info.isDirectory()) throw new SetupError("token_file_not_file", `權杖檔案 ${raw} 是目錄。`);
  const realInfo = await stat(await realpath(raw));
  if (!realInfo.isFile())
    throw new SetupError("token_file_not_file", `權杖檔案 ${raw} 不是一般檔案。`);
  if (realInfo.size === 0)
    throw new SetupError("token_file_empty", `權杖檔案 ${raw} 是空的；請寫入配接器權杖。`);
  if (realInfo.size > MAX_TOKEN_BYTES) {
    throw new SetupError(
      "token_file_too_large",
      `權杖檔案 ${raw} 為 ${realInfo.size} 位元組，超過 runtime 的 ${MAX_TOKEN_BYTES} 位元組上限；請確認內容是配接器權杖。`,
    );
  }
  const mode = realInfo.mode & 0o777;
  const ownerMode = mode.toString(8).padStart(4, "0");
  if ((mode & 0o077) !== 0) {
    warnings.push(`權杖檔案權限為 ${ownerMode}，建議執行 chmod 600 ${raw}。`);
  }
  if (isInside(projectRoot, raw)) {
    const rel = relative(projectRoot, raw).replaceAll("\\", "/");
    if (!rel.startsWith("secrets/") && rel !== ".omp/siyuan-memory.token") {
      warnings.push(
        `權杖檔案位於專案內（${rel}），請確認不會被 Git 追蹤（建議放在 secrets/ 或 .omp/siyuan-memory.token）。`,
      );
    }
  }
  return { path: raw, summary: `存在（${ownerMode}，${realInfo.size} 位元組）` };
}

/** 以內容 manifest 核對已建置配接器：輸出雜湊 + 所有建置來源的內容雜湊。 */
async function assertAdapterCurrent(artifactPath: string, manifestPath: string): Promise<void> {
  const stale = (detail: string): never => {
    throw new SetupError(
      "adapter_stale",
      `配接器 ${artifactPath} 與 ${ADAPTER_MANIFEST_NAME} 不符（${detail}）；請在來源專案重新執行 bun run build。`,
    );
  };
  let manifest: AdapterManifest;
  try {
    manifest = parseAdapterManifest(await readFile(manifestPath, "utf8"));
  } catch (error) {
    return stale(error instanceof Error ? error.message : String(error));
  }
  if (manifest.artifact.file !== basename(artifactPath))
    return stale(`manifest 記錄的輸出檔是 ${manifest.artifact.file}`);
  if ((await hashFile(artifactPath)) !== manifest.artifact.sha256)
    return stale("輸出檔內容與建置時不同");
  for (const [rel, digest] of Object.entries(manifest.inputs)) {
    const sourcePath = resolve(manifest.root, rel);
    if (!isInside(manifest.root, sourcePath)) return stale(`來源路徑 ${rel} 逸出 ${manifest.root}`);
    const actual = await hashFile(sourcePath).catch(() => null);
    if (actual === null) return stale(`來源 ${rel} 不存在或無法讀取`);
    if (actual !== digest) return stale(`來源 ${rel} 的內容已變更`);
  }
}

/** 驗證單一配接器 artifact（存在、非空、內容與 manifest 一致）並回傳其實際路徑。 */
async function inspectBuiltAdapter(
  raw: string,
  warnings: string[],
): Promise<{ path: string; summary: string }> {
  const target = resolve(raw);
  const info = await statOrNull(target);
  if (!info) {
    throw new SetupError(
      "adapter_missing",
      `找不到已建置的配接器 ${target}；請先執行 bun run build。`,
    );
  }
  const realInfo = await stat(await realpath(target));
  if (!realInfo.isFile())
    throw new SetupError("adapter_not_file", `配接器 ${target} 不是一般檔案。`);
  if (realInfo.size === 0)
    throw new SetupError("adapter_empty", `配接器 ${target} 是空的；請重新執行 bun run build。`);

  const manifestInfo = await statOrNull(join(dirname(target), ADAPTER_MANIFEST_NAME));
  const size = `${realInfo.size} 位元組`;
  if (manifestInfo && !manifestInfo.isFile())
    throw new SetupError(
      "adapter_manifest_invalid",
      `${join(dirname(target), ADAPTER_MANIFEST_NAME)} 不是一般檔案。`,
    );
  if (manifestInfo) {
    await assertAdapterCurrent(target, join(dirname(target), ADAPTER_MANIFEST_NAME));
    return { path: await realpath(target), summary: `已建置（${size}，內容核對通過）` };
  }
  if (isInside(REPO_ROOT, target)) {
    throw new SetupError(
      "adapter_manifest_missing",
      `${target} 缺少 ${ADAPTER_MANIFEST_NAME}，無法確認是否與來源一致；請執行 bun run build 重新產出。`,
    );
  }
  warnings.push(
    `配接器 ${target} 位於來源專案外且沒有 ${ADAPTER_MANIFEST_NAME}，無法核對內容新鮮度。`,
  );
  return { path: await realpath(target), summary: `已建置（${size}，外部路徑未核對）` };
}

async function inspectAdapter(
  raw: string | undefined,
  warnings: string[],
): Promise<{ path: string; summary: string }> {
  return await inspectBuiltAdapter(
    raw ? resolve(process.cwd(), raw) : join(REPO_ROOT, ADAPTER_DEFAULT),
    warnings,
  );
}

/**
 * 專案 `config.yml` 是 local layer，而 OMP 對陣列鍵採「整份覆蓋」語意
 * （`Settings` 的 deepMerge 只遞迴純物件），專案層一旦寫入 `extensions` 或
 * `disabledExtensions`，全域清單就不再參與合併。兩份清單都必須把繼承來的項目
 * 顯式帶上，否則安裝會靜默丟掉使用者原本的全域擴充套件。
 */
interface InheritedSettings {
  disabledIds: string[];
  extensionIds: string[];
  path: string;
  exists: boolean;
}

function readStringList(map: YamlMap, key: string, sourcePath: string, code: string): string[] {
  const value = map[key];
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) {
    throw new SetupError(code, `${sourcePath} 的 ${key} 必須是字串清單。`);
  }
  return value as string[];
}

async function readGlobalSettings(path: string): Promise<InheritedSettings> {
  const info = await statOrNull(path);
  if (!info) return { disabledIds: [], extensionIds: [], path, exists: false };
  if (!info.isFile())
    throw new SetupError("global_settings_not_file", `全域設定 ${path} 不是一般檔案。`);
  // 只取 disabledExtensions 與 extensions。此檔可能含憑據，其他欄位不會被讀出、記錄或輸出。
  const text = await readFile(path, "utf8");
  const map = text.trim() === "" ? {} : parseSettingsMap(text, path);
  return {
    disabledIds: readStringList(
      map,
      "disabledExtensions",
      path,
      "global_disabled_extensions_invalid",
    ),
    extensionIds: readStringList(map, "extensions", path, "global_extensions_invalid"),
    path,
    exists: true,
  };
}

type YamlMap = Record<string, unknown>;

function parseSettingsMap(text: string, sourcePath: string): YamlMap {
  let parsed: unknown;
  try {
    parsed = Bun.YAML.parse(text);
  } catch {
    throw new SetupError(
      "settings_unreadable",
      `${sourcePath} 不是有效 YAML，請修復後再執行（本工具不覆寫無法解析的設定）。`,
    );
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new SetupError("settings_not_mapping", `${sourcePath} 的最上層必須是對應表。`);
  }
  return parsed as YamlMap;
}

function topLevelKey(line: string): string | null {
  const match = /^([A-Za-z_][\w.-]*):(\s|$)/.exec(line);
  return match?.[1] ?? null;
}

function blockEnd(lines: string[], start: number): number {
  let cursor = start + 1;
  while (cursor < lines.length) {
    const line = lines[cursor] ?? "";
    if (line !== "" && !/^[ \t]/.test(line)) break;
    cursor++;
  }
  let last = cursor;
  while (last > start + 1 && (lines[last - 1] ?? "").trim() === "") last--;
  return last;
}

function childIndent(lines: string[], start: number, end: number, fallback: string): string {
  for (let index = start + 1; index < end; index++) {
    const line = lines[index] ?? "";
    const match = /^([ \t]+)\S/.exec(line);
    if (match?.[1]) return match[1];
  }
  return fallback;
}

function formatScalar(value: unknown): string {
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (value === null) return "null";
  if (Array.isArray(value)) return `[${value.map((item) => formatScalar(item)).join(", ")}]`;
  throw new SetupError("settings_value_unsupported", `無法安全序列化 ${JSON.stringify(value)}。`);
}

function appendBlock(lines: string[], block: string[]): string[] {
  const result = [...lines];
  if (result.length > 0 && (result.at(-1) ?? "").trim() !== "") result.push("");
  return [...result, ...block];
}

/** 兩個可編輯的頂層清單鍵，以及各自的形狀錯誤碼。 */
type TopLevelSequenceKey = "disabledExtensions" | "extensions";

/**
 * `extensions` 條目是否已等價存在於現有清單。OMP 以 cwd（專案根目錄）解析相對
 * 條目（`resolvePath(configuredPath, cwd)`），這裡採同一規則，免得同一條目的
 * 相對／絕對寫法被誤判成未註冊而重複添加。
 */
function alreadyRegistered(entry: string, existing: string[], projectRoot: string): boolean {
  const target = resolve(projectRoot, entry);
  return existing.some((registered) => resolve(projectRoot, registered) === target);
}

const SEQUENCE_ERROR_CODES: Record<TopLevelSequenceKey, string> = {
  disabledExtensions: "settings_disabled_extensions_not_sequence",
  extensions: "settings_extensions_not_sequence",
};

/**
 * 頂層字串清單（`disabledExtensions`、`extensions`）的逐行編輯：保留既有項目與
 * 註解，只在缺少時附加。區塊與單行 `[…]` 形式都支援；無法安全改寫的形狀一律
 * 中止，不猜測語意。
 */
function ensureTopLevelSequence(
  lines: string[],
  map: YamlMap,
  key: TopLevelSequenceKey,
  additions: string[],
): string[] {
  const code = SEQUENCE_ERROR_CODES[key];
  const index = lines.findIndex((line) => topLevelKey(line) === key);
  if (index === -1) {
    if (additions.length === 0) return lines;
    return appendBlock(lines, [`${key}:`, ...additions.map((id) => `  - ${id}`)]);
  }
  const line = lines[index] ?? "";
  const tail = line.slice(line.indexOf(":") + 1).trim();
  if (tail === "" || tail.startsWith("#")) {
    const end = blockEnd(lines, index);
    for (let cursor = index + 1; cursor < end; cursor++) {
      const item = lines[cursor] ?? "";
      if (item.trim() === "" || /^\s*#/.test(item)) continue;
      if (!/^\s*-\s*\S/.test(item)) {
        throw new SetupError(
          code,
          `${SETTINGS_RELATIVE} 的 ${key} 必須是清單，第 ${cursor + 1} 行不是清單項目。`,
        );
      }
    }
    if (additions.length === 0) return lines;
    const indent = childIndent(lines, index, end, "  ");
    return [
      ...lines.slice(0, end),
      ...additions.map((id) => `${indent}- ${id}`),
      ...lines.slice(end),
    ];
  }
  if (!tail.startsWith("[") || !tail.endsWith("]")) {
    throw new SetupError(
      code,
      `${SETTINGS_RELATIVE} 的 ${key} 必須是清單（區塊或單行 […] 形式）。`,
    );
  }
  if (additions.length === 0) return lines;
  const existing = (map[key] ?? []) as string[];
  const next = [...existing, ...additions];
  return [
    ...lines.slice(0, index),
    `${key}: [${next.map((id) => formatScalar(id)).join(", ")}]`,
    ...lines.slice(index + 1),
  ];
}

function verifySettings(
  text: string,
  before: YamlMap,
  additions: string[],
  extensionAdditions: string[],
  sourcePath: string,
): void {
  const after = parseSettingsMap(text, sourcePath);
  const reject = (detail: string): never => {
    throw new SetupError(
      "settings_verify_failed",
      `套用後驗證失敗（${detail}），已中止且未寫入 ${sourcePath}。`,
    );
  };
  const disabled = after.disabledExtensions;
  if (disabled !== undefined) {
    if (!Array.isArray(disabled) || disabled.some((entry) => typeof entry !== "string"))
      reject("disabledExtensions 不是字串清單");
  }
  const disabledIds = Array.isArray(disabled) ? (disabled as string[]) : [];
  for (const id of additions) {
    if (!disabledIds.includes(id)) reject(`disabledExtensions 缺少 ${id}`);
  }
  const extensions = after.extensions;
  if (extensions === undefined) {
    // 只有「沒有擴充要註冊、原本也沒有清單」才允許缺席；其他情況代表編輯弄丟了東西。
    if (extensionAdditions.length > 0 || before.extensions !== undefined) reject("extensions 遺失");
  } else if (!Array.isArray(extensions) || extensions.some((entry) => typeof entry !== "string")) {
    reject("extensions 不是字串清單");
  }
  const extensionEntries = Array.isArray(extensions) ? (extensions as string[]) : [];
  for (const entry of extensionAdditions) {
    if (!extensionEntries.includes(entry)) reject(`extensions 缺少 ${entry}`);
  }
  // 本工具只被允許變動 extensions／disabledExtensions 兩個清單。其餘每個鍵——包含
  // hindsight.* 與 jev-memory-gate 的停用狀態——都必須逐字不變，否則就是安裝動到了
  // 別人擁有的設定。
  for (const [key, value] of Object.entries(before)) {
    if (key === "disabledExtensions" || key === "extensions") continue;
    if (!Bun.deepEquals(after[key], value)) reject(`既有鍵 ${key} 內容改變`);
  }
  for (const key of Object.keys(after)) {
    if (!(key in before) && key !== "disabledExtensions" && key !== "extensions")
      reject(`出現未預期的鍵 ${key}`);
  }
  const beforeDisabled = before.disabledExtensions;
  if (Array.isArray(beforeDisabled)) {
    for (const id of beforeDisabled as string[]) {
      if (!disabledIds.includes(id)) reject(`既有停用項目 ${id} 遺失`);
    }
  }
  const beforeExtensions = before.extensions;
  if (Array.isArray(beforeExtensions)) {
    for (const entry of beforeExtensions as string[]) {
      if (!extensionEntries.includes(entry)) reject(`既有擴充套件項目 ${entry} 遺失`);
    }
  }
}

function splitLines(text: string): { lines: string[]; eol: string } {
  const eol = text.includes("\r\n") ? "\r\n" : "\n";
  const normalized = eol === "\r\n" ? text.replaceAll("\r\n", "\n") : text;
  const lines = normalized.split("\n");
  if (lines.at(-1) === "") lines.pop();
  return { lines, eol };
}

function applyProjectSettings(
  text: string,
  additions: string[],
  extensionAdditions: string[],
  sourcePath: string,
): string {
  const before = text.trim() === "" ? {} : parseSettingsMap(text, sourcePath);
  const { lines, eol } =
    text.trim() === "" ? { lines: [] as string[], eol: "\n" } : splitLines(text);
  let edited = ensureTopLevelSequence(lines, before, "disabledExtensions", additions);
  edited = ensureTopLevelSequence(edited, before, "extensions", extensionAdditions);
  const result = `${edited.join(eol)}${eol}`;
  verifySettings(result, before, additions, extensionAdditions, sourcePath);
  return result;
}

async function planSettings(
  paths: TargetPaths,
  inherited: InheritedSettings,
  warnings: string[],
): Promise<SettingsPlan> {
  const info = await statOrNull(paths.settingsPath);
  if (info?.isSymbolicLink()) {
    throw new SetupError(
      "settings_is_symlink",
      `${paths.settingsPath} 是符號連結，本工具拒絕覆寫。`,
    );
  }
  const before = info ? await readFile(paths.settingsPath, "utf8") : "";
  const map = before.trim() === "" ? {} : parseSettingsMap(before, paths.settingsPath);
  const existingIds = readStringList(
    map,
    "disabledExtensions",
    paths.settingsPath,
    "settings_disabled_extensions_invalid",
  );
  const existingExtensions = readStringList(
    map,
    "extensions",
    paths.settingsPath,
    "settings_extensions_invalid",
  );
  // `disabledExtensions` 只在需要帶入繼承的全域項目時才補齊：專案層是整份覆蓋
  // 語意，不補就會讓使用者的全域停用清單消失。本工具不新增任何自己的停用項目。
  const additions = [...new Set(inherited.disabledIds)].filter((id) => !existingIds.includes(id));
  // 專案 stub 是 gitignored，只能靠這份顯式清單載入；繼承的全域條目先帶上，避免
  // 專案層的陣列覆蓋把使用者的全域擴充套件整份丟掉。
  const extensionAdditions = [...new Set([...inherited.extensionIds, paths.stubPath])].filter(
    (entry) => !alreadyRegistered(entry, existingExtensions, paths.root),
  );
  const text = applyProjectSettings(before, additions, extensionAdditions, paths.settingsPath);
  if (!inherited.exists) {
    warnings.push(`找不到全域設定 ${inherited.path}；只會處理專案層設定。`);
  }
  return {
    text,
    changed: text !== before,
    additions,
    extensionAdditions,
    globalIds: inherited.disabledIds,
    globalPath: inherited.path,
  };
}

async function inspectStub(stubPath: string): Promise<StubState> {
  const info = await statOrNull(stubPath);
  if (!info) return { exists: false, path: stubPath, boundPath: null };
  if (info.isSymbolicLink())
    throw new SetupError("stub_is_symlink", `${stubPath} 是符號連結，本工具拒絕覆寫。`);
  if (!info.isFile()) throw new SetupError("stub_not_file", `${stubPath} 不是一般檔案。`);
  const text = await readFile(stubPath, "utf8");
  if (!text.startsWith(STUB_MARKER)) {
    throw new SetupError(
      "stub_conflict",
      `${stubPath} 已存在但不是本工具產生的 stub；為避免覆寫其他工具的檔案，請先確認內容或移除它。`,
    );
  }
  const match = /^export \{ default \} from (.+);$/m.exec(text);
  let boundPath: string | null = null;
  if (match?.[1] !== undefined) {
    try {
      const specifier: unknown = JSON.parse(match[1]);
      if (typeof specifier === "string" && specifier !== "") {
        const resolved = isAbsolute(specifier) ? specifier : resolve(dirname(stubPath), specifier);
        boundPath = await realpath(resolved).catch(() => resolved);
      }
    } catch {
      boundPath = null;
    }
  }
  return { exists: true, path: stubPath, boundPath };
}

async function buildPlan(options: Options): Promise<Plan> {
  const projectRoot = await resolveProjectRoot(options.project);
  const paths = await resolveTargetPaths(options, projectRoot);
  const warnings: string[] = [];
  const existing = await readExistingConfig(paths.configPath);
  const projectId = requireFlag(options.projectId, "--project-id");
  if (!PROJECT_ID_PATTERN.test(projectId)) {
    throw new SetupError(
      "project_id_invalid",
      `--project-id ${projectId} 不符格式（^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$）。`,
    );
  }
  const serviceUrl = normalizeServiceUrl(requireFlag(options.serviceUrl, "--service-url"));
  const token = await inspectTokenFile(
    requireFlag(options.tokenFile, "--token-file"),
    projectRoot,
    warnings,
  );
  const adapter = await inspectAdapter(options.adapterPath, warnings);
  const stub = await inspectStub(paths.stubPath);
  // stub 就是 OMP 的實際載入路徑：既有繫結與本次驗證的配接器不同時，不得默默沿用。
  let stubAction: Plan["stubAction"] = "create";
  if (stub.exists) {
    if (stub.boundPath === adapter.path) {
      stubAction = "keep";
    } else if (!options.reconfigure) {
      throw new SetupError(
        "stub_requires_reconfigure",
        `既有 stub ${paths.stubPath} 繫結的是 ${stub.boundPath ?? "無法解析的配接器路徑"}，` +
          `與本次驗證的 ${adapter.path} 不同。請確認後加上 --reconfigure 重新執行，讓 stub 改繫結到實際要載入的配接器。`,
      );
    } else {
      stubAction = "rewrite";
    }
  }
  const scopeChanges: string[] = [];
  if (existing) {
    const scope: Array<[string, string, string]> = [
      ["projectId", projectId, existing.projectId],
      ["projectRoot", projectRoot, existing.projectRoot],
      ["serviceUrl", serviceUrl, existing.serviceUrl],
      ["tokenFile", token.path, existing.tokenFile],
      ["stateDir", paths.stateDir, existing.stateDir],
    ];
    for (const [name, next, previous] of scope) {
      if (next !== previous) scopeChanges.push(name);
    }
    if (scopeChanges.length > 0 && !options.reconfigure) {
      throw new SetupError(
        "scope_change_requires_reconfigure",
        `既有啟用設定的 ${scopeChanges.join("、")} 與本次參數不同。為避免靜默改變專案或權杖範圍，請確認後加上 --reconfigure 重新執行。`,
      );
    }
  }
  const explicit = options.activatedAt ? validateIsoTime(options.activatedAt) : null;
  const boundaryReset =
    existing !== null &&
    options.reconfigure &&
    (scopeChanges.includes("projectId") || scopeChanges.includes("projectRoot"));
  let activatedAt: string;
  let activatedAtSource: string;
  if (!existing) {
    activatedAt = explicit ?? new Date().toISOString();
    activatedAtSource = explicit ? "本次指定" : "本次建立";
  } else if (boundaryReset) {
    activatedAt = explicit ?? new Date().toISOString();
    activatedAtSource = "重新界定";
  } else if (explicit && explicit !== existing.activatedAt) {
    if (!options.reconfigure) {
      throw new SetupError(
        "activation_boundary_locked",
        `既有啟用時間為 ${existing.activatedAt}；變更它會重新界定捕獲起點。請加上 --reconfigure，或省略 --activated-at 以沿用原值。`,
      );
    }
    activatedAt = explicit;
    activatedAtSource = "本次指定";
  } else {
    activatedAt = existing.activatedAt;
    activatedAtSource = "沿用既有";
  }
  const config: MemoryConfig = {
    schemaVersion: 1,
    enabled: true,
    projectId,
    projectRoot,
    serviceUrl,
    tokenFile: token.path,
    stateDir: paths.stateDir,
    activatedAt,
  };
  const inherited = await readGlobalSettings(
    await resolveGlobalConfigPath(options.globalConfigPath),
  );
  const settings = await planSettings(paths, inherited, warnings);
  return {
    options,
    paths,
    config,
    activatedAtSource,
    scopeChanges,
    tokenSummary: token.summary,
    adapterSummary: adapter.summary,
    adapterPath: adapter.path,
    stubAction,
    settings,
    stub,
    warnings,
  };
}

async function writeAtomic(target: string, content: string, defaultMode: number): Promise<void> {
  const existing = await statOrNull(target);
  const mode = existing ? existing.mode & 0o777 : defaultMode;
  const temp = join(dirname(target), `.${basename(target)}.${process.pid}.tmp`);
  try {
    await writeFile(temp, content, { mode });
    const handle = await open(temp, "r+");
    try {
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temp, target);
  } catch (error) {
    await unlink(temp).catch(() => undefined);
    throw error;
  }
}

const STUB_ACTION_LABEL: Record<Plan["stubAction"], string> = {
  create: "將建立並繫結本次驗證的配接器",
  keep: "已繫結同一個配接器",
  rewrite: "將重寫為本次驗證的配接器",
};

function printPlan(plan: Plan): void {
  const lines = [
    "OMP 知識發布配接器設定（dry-run，未寫入任何檔案）",
    `  專案根目錄   : ${plan.paths.root}`,
    `  專案 ID      : ${plan.config.projectId}`,
    `  服務網址     : ${plan.config.serviceUrl}（須與伺服器 PUBLIC_ORIGIN 一致）`,
    `  權杖檔案     : ${plan.config.tokenFile}（${plan.tokenSummary}）`,
    `  狀態目錄     : ${plan.config.stateDir}`,
    `  設定檔       : ${plan.paths.configPath}`,
    `  擴充套件 stub : ${plan.paths.stubPath}（${STUB_ACTION_LABEL[plan.stubAction]}）`,
    `  專案設定     : ${plan.paths.settingsPath}（${plan.settings.changed ? "將更新" : "已符合"}）`,
    `  配接器       : ${plan.adapterPath}（${plan.adapterSummary}）`,
    `  啟用時間     : ${plan.config.activatedAt}（${plan.activatedAtSource}）`,
    `  擴充註冊     : ${
      plan.settings.extensionAdditions.length > 0
        ? `將註冊 ${plan.settings.extensionAdditions.join("、")}`
        : `已註冊 ${plan.paths.stubPath}`
    }`,
    `  停用清單帶入 : ${plan.settings.additions.length > 0 ? plan.settings.additions.join("、") : "無需變更（既有項目原樣保留）"}`,
    `  其他設定     : 不變更（hindsight.* 與既有停用項目原樣保留）`,
    `  狀態目錄內容 : 保留不動（不重設佇列）`,
  ];
  if (plan.settings.globalIds.length > 0) {
    lines.splice(
      lines.length - 1,
      0,
      `  全域停用來源 : ${plan.settings.globalIds.length} 項來自 ${plan.settings.globalPath}`,
    );
  }
  for (const warning of plan.warnings) lines.push(`  警告         : ${warning}`);
  console.info(lines.join("\n"));
  console.info("dry-run：未寫入任何檔案。加上 --apply 才會寫入設定檔、stub 與專案設定。");
}

function printApplied(plan: Plan): void {
  const lines = [
    "OMP 知識發布配接器設定完成（僅限本專案）",
    `  設定檔       : ${plan.paths.configPath}`,
    `  擴充套件 stub : ${plan.paths.stubPath}（${STUB_ACTION_LABEL[plan.stubAction]}）`,
    `  配接器       : ${plan.adapterPath}（${plan.adapterSummary}）`,
    `  專案設定     : ${plan.paths.settingsPath}${plan.settings.changed ? "" : "（未變更）"}`,
    `  擴充註冊     : ${plan.paths.stubPath}（extensions 顯式註冊，不受 gitignore 影響）`,
    `  其他設定     : 未變更（hindsight.* 與既有停用項目原樣保留）`,
    `  狀態目錄     : ${plan.config.stateDir}（內容保留）`,
    `  啟用時間     : ${plan.config.activatedAt}（${plan.activatedAtSource}）`,
  ];
  for (const warning of plan.warnings) lines.push(`  警告         : ${warning}`);
  console.info(lines.join("\n"));
  console.info("請在新的一輪 OMP 工作階段開始後才會生效；其他專案未受影響。");
}

async function applyPlan(plan: Plan): Promise<void> {
  await mkdir(dirname(plan.paths.configPath), { recursive: true, mode: 0o700 });
  await mkdir(dirname(plan.paths.stubPath), { recursive: true, mode: 0o700 });
  await mkdir(plan.config.stateDir, { recursive: true, mode: 0o700 });
  // 順序就是 fail-closed：先把 stub 註冊進專案設定，再放上可載入的 stub 檔，最後才
  // 寫入代表啟用的設定檔。任何一步失敗都不會留下「已啟用但載不到配接器」。本工具不
  // 碰任何其他記憶擁有者的設定，因此沒有「先讓別人退場」這種步驟。
  if (plan.settings.changed) await writeAtomic(plan.paths.settingsPath, plan.settings.text, 0o644);
  if (plan.stubAction !== "keep")
    await writeAtomic(plan.paths.stubPath, generatedStub(plan.adapterPath), 0o644);
  await writeAtomic(plan.paths.configPath, `${JSON.stringify(plan.config, null, 2)}\n`, 0o600);
}

async function reportStatus(options: Options): Promise<number> {
  const projectRoot = await resolveProjectRoot(options.project);
  const configPath = resolveConfigPath(options, projectRoot);
  const rows: string[] = [];
  const problems: string[] = [];
  rows.push(`  設定檔       : ${configPath}`);
  let config: MemoryConfig | null = null;
  const info = await statOrNull(configPath);
  if (!info) {
    rows.push("  啟用狀態     : 未設定");
    problems.push("config_missing: 尚未啟用：找不到設定檔。");
  } else {
    try {
      config = parseMemoryConfig(JSON.parse(await readFile(configPath, "utf8")), configPath);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      rows.push("  啟用狀態     : 設定無效");
      problems.push(`config_invalid: ${detail}`);
    }
  }
  if (config) {
    rows.push(`  啟用狀態     : ${config.enabled ? "已啟用" : "已停用"}`);
    rows.push(`  專案 ID      : ${config.projectId}`);
    rows.push(`  專案根目錄   : ${config.projectRoot}`);
    rows.push(`  服務網址     : ${config.serviceUrl}`);
    rows.push(`  啟用時間     : ${config.activatedAt}`);
    if (!config.enabled) problems.push("config_disabled: 設定存在但 enabled 為 false。");
    const rootInfo = await statOrNull(config.projectRoot);
    if (!rootInfo?.isDirectory()) {
      problems.push(`project_root_missing: 專案根目錄不存在或不是目錄：${config.projectRoot}`);
    }
    if (options.project && (await resolveProjectRoot(options.project)) !== config.projectRoot) {
      problems.push(
        `project_root_mismatch: 設定的專案根目錄與目前 --project 不同（${config.projectRoot}）。`,
      );
    }
    const tokenInfo = await statOrNull(config.tokenFile);
    if (!tokenInfo) {
      rows.push(`  權杖檔案     : ${config.tokenFile}（不存在）`);
      problems.push(`token_file_missing: 權杖檔案不存在：${config.tokenFile}`);
    } else {
      const realInfo = await stat(await realpath(config.tokenFile)).catch(() => null);
      if (!realInfo?.isFile() || realInfo.size === 0) {
        rows.push(`  權杖檔案     : ${config.tokenFile}（無法讀取或為空）`);
        problems.push(`token_file_unusable: 權杖檔案無法讀取或為空：${config.tokenFile}`);
      } else if (realInfo.size > MAX_TOKEN_BYTES) {
        rows.push(
          `  權杖檔案     : ${config.tokenFile}（${realInfo.size} 位元組，超過 ${MAX_TOKEN_BYTES} 位元組上限）`,
        );
        problems.push(
          `token_file_too_large: 權杖檔案超過 runtime 的 ${MAX_TOKEN_BYTES} 位元組上限：${config.tokenFile}`,
        );
      } else {
        rows.push(
          `  權杖檔案     : ${config.tokenFile}（存在，${(realInfo.mode & 0o777).toString(8).padStart(4, "0")}）`,
        );
      }
    }
    const stateInfo = await statOrNull(config.stateDir);
    rows.push(
      `  狀態目錄     : ${config.stateDir}（${stateInfo?.isDirectory() ? "存在" : "不存在"}）`,
    );
    if (!stateInfo?.isDirectory())
      problems.push(`state_dir_missing: 狀態目錄不存在：${config.stateDir}`);
  }
  const explicitAdapter = options.adapterPath ? resolve(process.cwd(), options.adapterPath) : null;
  const stubPath = join(projectRoot, STUB_RELATIVE);
  let stub: StubState | null = null;
  try {
    stub = await inspectStub(stubPath);
  } catch (error) {
    rows.push("  擴充套件 stub : 內容不符");
    problems.push(
      `${error instanceof SetupError ? error.code : "stub_conflict"}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  if (stub) {
    if (!stub.exists) {
      rows.push("  擴充套件 stub : 不存在");
      problems.push("stub_missing: 擴充套件 stub 不存在。");
    } else if (stub.boundPath === null) {
      rows.push("  擴充套件 stub : 沒有可解析的配接器匯入路徑");
      problems.push("stub_unbound: 擴充套件 stub 無法解析出要載入的配接器路徑。");
    } else {
      rows.push(`  擴充套件 stub : 繫結 ${stub.boundPath}`);
    }
  }
  // 就緒與否只看 stub 真正繫結、也就是 OMP 實際會載入的那個 artifact。未指定
  // --adapter 時不去檢查來源專案的預設建置輸出：那和這個專案的載入路徑無關，拿它當
  // 判準只會對從別的 checkout 或別台機器安裝的專案給出假降級。
  const boundPath = stub?.boundPath ?? null;
  if (
    explicitAdapter !== null &&
    boundPath !== null &&
    !(await sameFile(explicitAdapter, boundPath))
  ) {
    problems.push(
      `stub_adapter_mismatch: --adapter 指定 ${explicitAdapter}，但 stub 繫結的是 ${boundPath}；請改用實際載入的配接器，或以 --reconfigure 重新安裝。`,
    );
  }
  const adapterWarnings: string[] = [];
  const judgedAdapter = boundPath ?? explicitAdapter;
  if (judgedAdapter === null) {
    rows.push("  配接器       : 未檢查（未指定 --adapter，且 stub 沒有可解析的繫結路徑）");
  } else {
    try {
      const adapter = await inspectBuiltAdapter(judgedAdapter, adapterWarnings);
      rows.push(`  配接器       : ${adapter.path}（${adapter.summary}）`);
    } catch (error) {
      rows.push(`  配接器       : ${judgedAdapter}（無法載入）`);
      problems.push(
        `${error instanceof SetupError ? error.code : "adapter_check_failed"}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
  for (const warning of adapterWarnings) rows.push(`  提示         : ${warning}`);
  const settingsPath = join(projectRoot, SETTINGS_RELATIVE);
  const settingsInfo = await statOrNull(settingsPath);
  if (!settingsInfo) {
    rows.push("  專案設定     : 不存在");
    problems.push(`settings_missing: 找不到 ${settingsPath}。`);
  } else {
    try {
      const map = parseSettingsMap(await readFile(settingsPath, "utf8"), settingsPath);
      const registered = alreadyRegistered(
        stubPath,
        readStringList(map, "extensions", settingsPath, "settings_extensions_invalid"),
        projectRoot,
      );
      rows.push(`  擴充註冊     : ${registered ? "已顯式註冊 stub" : "未註冊 stub（不會被載入）"}`);
      rows.push("  記憶體擁有權 : 不主張（Hindsight 與 gate 設定原樣保留）");
      if (!registered)
        problems.push(
          `stub_not_registered: ${settingsPath} 的 extensions 未包含 ${stubPath}；stub 為 gitignored，未被顯式註冊就不會被 OMP 載入。`,
        );
    } catch (error) {
      problems.push(
        `${error instanceof SetupError ? error.code : "settings_unreadable"}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
  const ready = problems.length === 0 && config !== null;
  rows.push(`  就緒狀態     : ${ready ? "就緒" : config ? "降級" : "未啟用"}`);
  for (const problem of problems) rows.push(`  問題         : ${problem}`);
  console.info(`OMP 知識發布配接器狀態\n${rows.join("\n")}`);
  return ready ? 0 : 1;
}

function reportError(error: unknown): number {
  if (error instanceof SetupError) {
    console.error(`錯誤（${error.code}）：${error.message}`);
    return error.exitCode;
  }
  console.error(error);
  return 1;
}

async function main(): Promise<number> {
  let options: Options;
  try {
    options = parseArgs(process.argv.slice(2));
  } catch (error) {
    return reportError(error);
  }
  if (options.help) {
    console.info(USAGE);
    return 0;
  }
  try {
    if (options.status) return await reportStatus(options);
    const plan = await buildPlan(options);
    if (!plan.options.apply) {
      printPlan(plan);
      return 0;
    }
    await applyPlan(plan);
    printApplied(plan);
    return 0;
  } catch (error) {
    return reportError(error);
  }
}

process.exitCode = await main();
